### ISSUE TITLE
css nesting rules seems not work

### ISSUE THREAD

**Issue by kuleyu** [brandonpittman/gridsome-plugin-tailwindcss#63]
Hi, this may not an issue, but a question. 

i configured `gridsome.config.js` as follows:
```js 
{
      use: "gridsome-plugin-tailwindcss",
      options: {
        tailwindConfig: './tailwind.config.js',
        presetEnvConfig: {
          features: {
            'nesting-rules': true
          }
        },
        shouldImport: true,
        shouldTimeTravel: true
      }
    }
```
then wrote  css by  nesting style like this:
```css
.nesting__dot button {
  background: #888111;
}
.nesting {
	color: aqua;
  &__actions {
    margin-top: 20px;
  }
  &__nav-button {
    background: transparent;
    border: none;
    color: #ccc;
    cursor: pointer;
    font-size: 24px;
    transition-duration: 0.3s;
    &:hover {
      color: #888;
    }
  }
  &__dot {
    margin: 0 10px;

    button {
      @apply bg-green-400;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: block;
      height: 10px;
      font-size: 0;
      line-height: 0;
      margin: 0;
      padding: 0;
      transition-duration: 0.3s;
      width: 10px;
    }
    &--current,
    &:hover {
      button {
        background-color: #888;
      }
    }
  }
}

```
No error reported, but the style didn't work. 
Is something else i need to do?
